#pragma line 1 "simple_vec_dot_product_terminate.c" ::: 0
#pragma line 1 "simple_vec_dot_product_terminate.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "simple_vec_dot_product_terminate.c" 2 ::: 194
#pragma line 1 "./simple_vec_dot_product.h" 1 ::: 204
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 217
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 258
#pragma line 13 "./simple_vec_dot_product.h" 2 ::: 261
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 262
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 287
#pragma line 128 "/usr/include/features.h" 3 4 ::: 388
#pragma line 149 "/usr/include/features.h" 3 4 ::: 402
#pragma line 177 "/usr/include/features.h" 3 4 ::: 404
#pragma line 193 "/usr/include/features.h" 3 4 ::: 407
#pragma line 350 "/usr/include/features.h" 3 4 ::: 438
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 442
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 477
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 483
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 506
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 547
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 553
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 571
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 577
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 581
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 583
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 587
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 597
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 650
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 691
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 712
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 736
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 737
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 739
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 741
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 742
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 767
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 778
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 783
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 784
#pragma line 25 "/usr/include/stdlib.h" 2 3 4 ::: 785
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 794
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 819
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 822
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 832
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 861
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 879
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 880
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 936
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 937
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 974
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 976
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 980
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 983
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1001
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1002
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1030
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1032
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1034
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1095
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1102
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1120
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1125
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1136
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1205
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1206
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1208
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1210
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 1218
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1236
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1239
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1242
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 1244
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 1245
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 1279
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 1285
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 1301
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 1303
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 1425
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 1439
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1460
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1477
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1505
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1531
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1532
#pragma line 58 "/usr/include/time.h" 3 4 ::: 1553
#pragma line 74 "/usr/include/time.h" 3 4 ::: 1556
#pragma line 90 "/usr/include/time.h" 3 4 ::: 1559
#pragma line 102 "/usr/include/time.h" 3 4 ::: 1562
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1565
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1566
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1567
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1592
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1595
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1605
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 1640
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 1671
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1694
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1696
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 1698
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1699
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 1703
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1743
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1754
#pragma line 118 "/usr/include/time.h" 3 4 ::: 1775
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1783
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 1785
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1820
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 1865
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1895
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 1899
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1917
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1928
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1930
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1952
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 1956
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1978
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1980
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 1982
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1983
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2006
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2026
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2096
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2127
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 2128
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 2271
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 2300
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2325
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2350
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 2353
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 2362
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 2375
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 2382
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 2394
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 2405
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 2452
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 2461
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 2468
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 2474
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 2489
#pragma line 912 "/usr/include/stdlib.h" 3 4 ::: 2640
#pragma line 948 "/usr/include/stdlib.h" 3 4 ::: 2642
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 2651
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 2669
#pragma line 14 "./simple_vec_dot_product.h" 2 ::: 2672
#pragma line 1 "./rtwtypes.h" 1 ::: 2673
#pragma line 140 "./rtwtypes.h" ::: 2795
#pragma line 150 "./rtwtypes.h" ::: 2797
#pragma line 15 "./simple_vec_dot_product.h" 2 ::: 2812
#pragma line 1 "./simple_vec_dot_product_types.h" 1 ::: 2813
#pragma line 16 "./simple_vec_dot_product.h" 2 ::: 2833
#pragma line 10 "simple_vec_dot_product_terminate.c" 2 ::: 2845
#pragma line 1 "./simple_vec_dot_product_terminate.h" 1 ::: 2846
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 2859
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 2884
#pragma line 13 "./simple_vec_dot_product_terminate.h" 2 ::: 2887
#pragma line 11 "simple_vec_dot_product_terminate.c" 2 ::: 2902
