#pragma line 1 "simple_vec_dot_product_initialize.c" ::: -10
#pragma line 1 "simple_vec_dot_product_initialize.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "simple_vec_dot_product_initialize.c" 2 ::: 184
#pragma line 1 "./simple_vec_dot_product.h" 1 ::: 194
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 207
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 248
#pragma line 13 "./simple_vec_dot_product.h" 2 ::: 251
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 252
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 277
#pragma line 128 "/usr/include/features.h" 3 4 ::: 378
#pragma line 149 "/usr/include/features.h" 3 4 ::: 392
#pragma line 177 "/usr/include/features.h" 3 4 ::: 394
#pragma line 193 "/usr/include/features.h" 3 4 ::: 397
#pragma line 350 "/usr/include/features.h" 3 4 ::: 428
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 432
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 467
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 473
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 496
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 543
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 561
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 567
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 571
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 573
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 577
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 587
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 640
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 681
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 702
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 726
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 727
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 729
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 731
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 732
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 757
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 768
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 773
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 774
#pragma line 25 "/usr/include/stdlib.h" 2 3 4 ::: 775
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 784
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 809
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 812
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 822
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 851
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 869
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 870
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 926
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 927
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 964
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 966
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 970
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 973
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 991
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 992
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1020
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1022
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1024
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1085
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1092
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1110
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1115
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1126
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1195
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1196
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1198
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1200
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 1208
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1226
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1229
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1232
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 1234
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 1235
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 1269
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 1275
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 1291
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 1293
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 1415
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 1429
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1450
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1467
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1495
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1521
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1522
#pragma line 58 "/usr/include/time.h" 3 4 ::: 1543
#pragma line 74 "/usr/include/time.h" 3 4 ::: 1546
#pragma line 90 "/usr/include/time.h" 3 4 ::: 1549
#pragma line 102 "/usr/include/time.h" 3 4 ::: 1552
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1555
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1556
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1557
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1582
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1585
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1595
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 1630
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 1661
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1684
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1686
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 1688
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1689
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 1693
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1733
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1744
#pragma line 118 "/usr/include/time.h" 3 4 ::: 1765
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1773
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 1775
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1810
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 1855
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1885
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 1889
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1907
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1918
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1920
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1942
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 1946
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1968
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1970
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 1972
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1973
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1996
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2016
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2086
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2117
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 2118
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 2261
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 2290
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2315
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2340
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 2343
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 2352
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 2365
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 2372
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 2384
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 2395
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 2442
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 2451
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 2458
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 2464
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 2479
#pragma line 912 "/usr/include/stdlib.h" 3 4 ::: 2630
#pragma line 948 "/usr/include/stdlib.h" 3 4 ::: 2632
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 2641
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 2659
#pragma line 14 "./simple_vec_dot_product.h" 2 ::: 2662
#pragma line 1 "./rtwtypes.h" 1 ::: 2663
#pragma line 140 "./rtwtypes.h" ::: 2785
#pragma line 150 "./rtwtypes.h" ::: 2787
#pragma line 15 "./simple_vec_dot_product.h" 2 ::: 2802
#pragma line 1 "./simple_vec_dot_product_types.h" 1 ::: 2803
#pragma line 16 "./simple_vec_dot_product.h" 2 ::: 2823
#pragma line 10 "simple_vec_dot_product_initialize.c" 2 ::: 2835
#pragma line 1 "./simple_vec_dot_product_initialize.h" 1 ::: 2836
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 2849
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 2874
#pragma line 13 "./simple_vec_dot_product_initialize.h" 2 ::: 2877
#pragma line 11 "simple_vec_dot_product_initialize.c" 2 ::: 2892
