#pragma line 1 "multiplication.c" ::: -10
#pragma line 1 "multiplication.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "multiplication.c" 2 ::: 184
#pragma line 1 "./multiplication.h" 1 ::: 197
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 213
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 254
#pragma line 16 "./multiplication.h" 2 ::: 257
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 258
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 283
#pragma line 128 "/usr/include/features.h" 3 4 ::: 384
#pragma line 149 "/usr/include/features.h" 3 4 ::: 398
#pragma line 177 "/usr/include/features.h" 3 4 ::: 400
#pragma line 193 "/usr/include/features.h" 3 4 ::: 403
#pragma line 350 "/usr/include/features.h" 3 4 ::: 434
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 438
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 473
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 479
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 502
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 543
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 549
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 567
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 573
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 577
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 579
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 583
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 593
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 646
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 687
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 708
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 732
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 733
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 735
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 737
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 738
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 763
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 774
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 779
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 780
#pragma line 25 "/usr/include/stdlib.h" 2 3 4 ::: 781
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 790
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 815
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 818
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 828
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 857
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 875
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 876
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 932
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 933
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 970
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 972
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 976
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 979
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 997
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 998
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1026
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1028
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1030
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1091
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1098
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1116
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1121
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1132
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1201
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1202
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1204
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1206
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 1214
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1232
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1235
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1238
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 1240
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 1241
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 1275
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 1281
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 1297
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 1299
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 1421
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 1435
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1456
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1473
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1501
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1527
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1528
#pragma line 58 "/usr/include/time.h" 3 4 ::: 1549
#pragma line 74 "/usr/include/time.h" 3 4 ::: 1552
#pragma line 90 "/usr/include/time.h" 3 4 ::: 1555
#pragma line 102 "/usr/include/time.h" 3 4 ::: 1558
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1561
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1562
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1563
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1588
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1591
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1601
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 1636
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 1667
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1690
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1692
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 1694
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1695
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 1699
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1739
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1750
#pragma line 118 "/usr/include/time.h" 3 4 ::: 1771
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1779
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 1781
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1816
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 1861
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1891
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 1895
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1913
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1924
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1926
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1948
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 1952
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1974
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1976
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 1978
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1979
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2002
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2022
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2092
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2123
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 2124
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 2267
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 2296
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2321
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2346
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 2349
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 2358
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 2371
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 2378
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 2390
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 2401
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 2448
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 2457
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 2464
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 2470
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 2485
#pragma line 912 "/usr/include/stdlib.h" 3 4 ::: 2636
#pragma line 948 "/usr/include/stdlib.h" 3 4 ::: 2638
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 2647
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 2665
#pragma line 17 "./multiplication.h" 2 ::: 2668
#pragma line 1 "./rtwtypes.h" 1 ::: 2669
#pragma line 140 "./rtwtypes.h" ::: 2792
#pragma line 151 "./rtwtypes.h" ::: 2794
#pragma line 18 "./multiplication.h" 2 ::: 2809
#pragma line 1 "./multiplication_types.h" 1 ::: 2810
#pragma line 19 "./multiplication.h" 2 ::: 2833
#pragma line 13 "multiplication.c" 2 ::: 2845
