#pragma line 1 "multiplication_terminate.c" ::: 0
#pragma line 1 "multiplication_terminate.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "multiplication_terminate.c" 2 ::: 194
#pragma line 1 "./multiplication.h" 1 ::: 207
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 223
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 264
#pragma line 16 "./multiplication.h" 2 ::: 267
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 268
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 293
#pragma line 128 "/usr/include/features.h" 3 4 ::: 394
#pragma line 149 "/usr/include/features.h" 3 4 ::: 408
#pragma line 177 "/usr/include/features.h" 3 4 ::: 410
#pragma line 193 "/usr/include/features.h" 3 4 ::: 413
#pragma line 350 "/usr/include/features.h" 3 4 ::: 444
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 448
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 483
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 489
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 512
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 553
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 559
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 577
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 583
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 587
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 589
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 593
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 603
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 656
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 697
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 718
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 742
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 743
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 745
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 747
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 748
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 773
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 784
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 789
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 790
#pragma line 25 "/usr/include/stdlib.h" 2 3 4 ::: 791
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 800
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 825
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 828
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 838
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 867
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 885
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 886
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 942
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 943
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 980
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 982
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 986
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 989
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1007
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1008
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1036
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1038
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1040
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1101
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1108
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1126
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1131
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1142
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1211
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1212
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1214
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1216
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 1224
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1242
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1245
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1248
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 1250
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 1251
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 1285
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 1291
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 1307
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 1309
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 1431
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 1445
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1466
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1483
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1511
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1537
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1538
#pragma line 58 "/usr/include/time.h" 3 4 ::: 1559
#pragma line 74 "/usr/include/time.h" 3 4 ::: 1562
#pragma line 90 "/usr/include/time.h" 3 4 ::: 1565
#pragma line 102 "/usr/include/time.h" 3 4 ::: 1568
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1571
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1572
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1573
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1598
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1601
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1611
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 1646
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 1677
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1700
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1702
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 1704
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1705
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 1709
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1749
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1760
#pragma line 118 "/usr/include/time.h" 3 4 ::: 1781
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1789
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 1791
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1826
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 1871
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1901
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 1905
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1923
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1934
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1936
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1958
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 1962
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1984
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1986
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 1988
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1989
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2012
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2032
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2102
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2133
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 2134
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 2277
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 2306
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2331
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2356
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 2359
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 2368
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 2381
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 2388
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 2400
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 2411
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 2458
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 2467
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 2474
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 2480
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 2495
#pragma line 912 "/usr/include/stdlib.h" 3 4 ::: 2646
#pragma line 948 "/usr/include/stdlib.h" 3 4 ::: 2648
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 2657
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 2675
#pragma line 17 "./multiplication.h" 2 ::: 2678
#pragma line 1 "./rtwtypes.h" 1 ::: 2679
#pragma line 140 "./rtwtypes.h" ::: 2802
#pragma line 151 "./rtwtypes.h" ::: 2804
#pragma line 18 "./multiplication.h" 2 ::: 2819
#pragma line 1 "./multiplication_types.h" 1 ::: 2820
#pragma line 19 "./multiplication.h" 2 ::: 2843
#pragma line 13 "multiplication_terminate.c" 2 ::: 2855
#pragma line 1 "./multiplication_terminate.h" 1 ::: 2856
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 2872
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 2897
#pragma line 16 "./multiplication_terminate.h" 2 ::: 2900
#pragma line 14 "multiplication_terminate.c" 2 ::: 2915
