#pragma line 1 "rt_nonfinite.c" ::: -10
#pragma line 1 "rt_nonfinite.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "rt_nonfinite.c" 2 ::: 184
#pragma line 1 "./rt_nonfinite.h" 1 ::: 201
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 219
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 260
#pragma line 18 "./rt_nonfinite.h" 2 ::: 263
#pragma line 1 "./rtwtypes.h" 1 ::: 264
#pragma line 140 "./rtwtypes.h" ::: 387
#pragma line 151 "./rtwtypes.h" ::: 389
#pragma line 19 "./rt_nonfinite.h" 2 ::: 404
#pragma line 17 "rt_nonfinite.c" 2 ::: 445
#pragma line 1 "./rtGetNaN.h" 1 ::: 446
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 460
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 485
#pragma line 14 "./rtGetNaN.h" 2 ::: 488
#pragma line 18 "rt_nonfinite.c" 2 ::: 502
#pragma line 1 "./rtGetInf.h" 1 ::: 503
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 517
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 542
#pragma line 14 "./rtGetInf.h" 2 ::: 545
#pragma line 19 "rt_nonfinite.c" 2 ::: 561
