#pragma line 1 "rt_nonfinite.c" ::: 0
#pragma line 1 "rt_nonfinite.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "rt_nonfinite.c" 2 ::: 194
#pragma line 1 "./rt_nonfinite.h" 1 ::: 211
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 229
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 270
#pragma line 18 "./rt_nonfinite.h" 2 ::: 273
#pragma line 1 "./rtwtypes.h" 1 ::: 274
#pragma line 140 "./rtwtypes.h" ::: 397
#pragma line 151 "./rtwtypes.h" ::: 399
#pragma line 19 "./rt_nonfinite.h" 2 ::: 414
#pragma line 17 "rt_nonfinite.c" 2 ::: 455
#pragma line 1 "./rtGetNaN.h" 1 ::: 456
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 470
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 495
#pragma line 14 "./rtGetNaN.h" 2 ::: 498
#pragma line 18 "rt_nonfinite.c" 2 ::: 512
#pragma line 1 "./rtGetInf.h" 1 ::: 513
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 527
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 552
#pragma line 14 "./rtGetInf.h" 2 ::: 555
#pragma line 19 "rt_nonfinite.c" 2 ::: 571
