#pragma line 1 "rtGetNaN.c" ::: 0
#pragma line 1 "rtGetNaN.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "rtGetNaN.c" 2 ::: 194
#pragma line 1 "./rtGetNaN.h" 1 ::: 210
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 224
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 265
#pragma line 14 "./rtGetNaN.h" 2 ::: 268
#pragma line 1 "./rtwtypes.h" 1 ::: 269
#pragma line 140 "./rtwtypes.h" ::: 392
#pragma line 151 "./rtwtypes.h" ::: 394
#pragma line 15 "./rtGetNaN.h" 2 ::: 409
#pragma line 1 "./rt_nonfinite.h" 1 ::: 410
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 428
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 453
#pragma line 18 "./rt_nonfinite.h" 2 ::: 456
#pragma line 16 "./rtGetNaN.h" 2 ::: 498
#pragma line 16 "rtGetNaN.c" 2 ::: 510
