#pragma line 1 "rtGetInf.c" ::: -10
#pragma line 1 "rtGetInf.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "rtGetInf.c" 2 ::: 184
#pragma line 1 "./rtGetInf.h" 1 ::: 200
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 214
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 255
#pragma line 14 "./rtGetInf.h" 2 ::: 258
#pragma line 1 "./rtwtypes.h" 1 ::: 259
#pragma line 140 "./rtwtypes.h" ::: 382
#pragma line 151 "./rtwtypes.h" ::: 384
#pragma line 15 "./rtGetInf.h" 2 ::: 399
#pragma line 1 "./rt_nonfinite.h" 1 ::: 400
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 418
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 443
#pragma line 18 "./rt_nonfinite.h" 2 ::: 446
#pragma line 16 "./rtGetInf.h" 2 ::: 488
#pragma line 16 "rtGetInf.c" 2 ::: 502
